sudo: required
language: generic
#santhosh

services:
  - docker

before_install:
  - gem install bundler
  - bundle config set force_ruby_platform true
  - docker build -t santhoshdurai/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true santhoshdurai/react-test npm test

after_success:
  - docker build -t santhoshdurai/multi-client ./client
  - docker build -t santhoshdurai/multi-nginx ./nginx
  - docker build -t santhoshdurai/multi-server ./server
  - docker build -t santhoshdurai/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push santhoshdurai/multi-client
  - docker push santhoshdurai/multi-nginx
  - docker push santhoshdurai/multi-server
  - docker push santhoshdurai/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: Multi-docker-santhosh
  env: Multi-docker-santhosh-env
  bucket_name: elasticbeanstalk-ap-southeast-2-982081062263
  bucket_path: docker-multi-santhosh
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY